# This file was generated by GoReleaser. DO NOT EDIT.
class Trivy < Formula
  desc ""
  homepage "https://github.com/aquasecurity/trivy"
  version "99.99.103"

  if OS.mac?
    url "https://github.com/itaysk/trivy/releases/download/v99.99.103/trivy_99.99.103_macOS-64bit.tar.gz"
    sha256 "dcb98f12166e709867c92891a760b5110cd7a55f2a5ea1bc8caa1bac0ccef187"
  elsif OS.linux?
    url "https://github.com/itaysk/trivy/releases/download/v99.99.103/trivy_99.99.103_Linux-64bit.tar.gz"
    sha256 "fa24e1b62d36a09c57adbe6abca2706676ff7d8de08a7e2dec029605df171b8d"
  end
  
  depends_on "rpm"

  def install
    bin.install "trivy"
  end

  test do
    system "#{bin}/program --version"
  end
end
